In [1]:
# importing library
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Getting a specific element [row, column]
print(a[1, 4])

# Getting a specific row (kinda like list slicing)
print(a[0, :])

# Getting a specific column
print(a[:, 0])
print(a[:, 3])

# [startindex:endindex:step]
print(a[0, 1:6:2])

12
[1 2 3 4 5 6 7]
[1 8]
[ 4 11]
[2 4 6]


In [13]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
