In [1]:
import numpy as np
import sys

# multidimensional array manipulation/operation related python module
# numpy is much faster than lists coz numpy has a fixed type and uses lesser bytes than lists. it doesnt have to go through type checking
# lists are actually not contiguous in the memory
# single instruction, multiple data - SIMD


In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [1,2,3]])
print(b)

[[9. 8. 7.]
 [1. 2. 3.]]


In [4]:
# Get dimension
print("dimension of a: ", a.ndim)
print("dimension of b: ", b.ndim)

# Shape?    (rows, columns)
b.shape

# datatype
print("dtype of b: ", b.dtype)
print("Type of a should be int16 because we set that => dtype: ", a.dtype)

dimension of a:  1
dimension of b:  2
dtype of b:  float64
Type of a should be int16 because we set that => dtype:  int16
