In [2]:
import numpy as np

In [10]:
# different ways to initialise arrays
# np.zeros(5) give array([0.,0.,0.,0.,0.])
# can do something similar like np.ones(5) --> array([1.,1.,1.,1.,1.])

np.zeros((2,3,4)) # 2x3x4

# for any other number we can do
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [12]:
a = np.array([[1,2,3,4], [5,6,7,8]])
np.full_like(a, 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [14]:
np.random.rand(4,2,3)

array([[[0.9069906 , 0.58664353, 0.38260555],
        [0.86944714, 0.12061139, 0.68951366]],

       [[0.64943045, 0.38707006, 0.62583306],
        [0.40062707, 0.82306272, 0.64508264]],

       [[0.32306364, 0.71284433, 0.29206196],
        [0.10878181, 0.70348818, 0.26519994]],

       [[0.70489484, 0.99590235, 0.0697658 ],
        [0.81438901, 0.39317374, 0.45238514]]])

In [23]:
output = np.ones((5,5))
output[1, 1:-1] = 0
output[3, 1:-1] = 0
output[2, 1:-1:2] = 0
output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
# rather than the above we can do this
out = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

out[1:-1, 1:-1] = z

print(out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



### copying arrays

In [42]:
a = np.array([1,2,3])
b = a
b[0] = 100
print("a: ", a)
print("b: ", b)

# creates a deep copy

a:  [100   2   3]
b:  [100   2   3]


In [43]:
# hence be careful while copying arrays
b = a.copy()
b[0] = 200
print("a: ", a)
print("b: ", b)

a:  [100   2   3]
b:  [200   2   3]
