In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a+2)
print(a/2)
print(a*2)

[3 4 5]
[0.5 1.  1.5]
[2 4 6]


In [3]:
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [4]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

## Linear Algebra

In [10]:
a = np.ones((2,3))
b = np.full((3,2), 2)

# cant do a*b

np.matmul(a, b)

stats = np.array([1,2,3,4,5,6])
np.min(stats)
np.max(stats)

np.int64(6)

In [12]:
# reorganizing arrays
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape((8,1))
print(before)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [19]:
# loading data from a file
filedata = np.genfromtxt('../../csv_files/data.txt', delimiter=',')
print(filedata)

filedata = filedata.astype('int32')
print(filedata)

[[88. 14. 60. 48. 45. 93.  7. 31. 92. 66.]
 [ 1. 32. 85. 22. 15. 48. 27. 52. 69. 34.]
 [29. 89. 76. 32. 90. 75. 49. 45. 10. 10.]]
[[88 14 60 48 45 93  7 31 92 66]
 [ 1 32 85 22 15 48 27 52 69 34]
 [29 89 76 32 90 75 49 45 10 10]]


In [20]:
# boolean masking 
((filedata > 50) & (filedata < 100))

array([[ True, False,  True, False, False,  True, False, False,  True,
         True],
       [False, False,  True, False, False, False, False,  True,  True,
        False],
       [False,  True,  True, False,  True,  True, False, False, False,
        False]])