In [2]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a+2)
print(a/2)
print(a*2)

[3 4 5]
[0.5 1.  1.5]
[2 4 6]


In [8]:
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [9]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

## Linear Algebra

In [11]:
a = np.ones((2,3))
b = np.full((3,2), 2)

# cant do a*b

np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])